### ISSUE TITLE
change repository description

### ISSUE THREAD

**Issue by Intevel** [nuxtus/create-nuxtus#2]
Hello 💚 
I think it would certainly be cleaner if we update the repository description from `npx package for creating a new @nuxtus/nuxtus site` to  `📦 Quickly create a Nuxt 3 & Directus app`

**Comment by craigharman** [comment]
Thanks for the suggestion - I wanted to try and push people to the actual @nuxtus/nuxtus repo rather than this one, so I've updated as follows: `📦 Quickly create a Nuxt 3 & Directus app with the @nuxtus/nuxtus boilerplate.` I'll also add a link to @nuxtus/nuxtus at the top of the readme.
